<pre class='metadata'>
Title: Event Timing
Shortname: event-timing
Level: 1
Status: CG-DRAFT
Group: WICG
Repository: WICG/event-timing
URL: http://example.com/url-this-spec-will-live-at
Editor: Tim Dresser, Google https://chromium.org, tdresser@chromium.org
Abstract: A short description of your spec, one or two sentences.
</pre>

Introduction {#intro}
=====================

See https://github.com/tabatkins/bikeshed to get started.
